kind: Deployment
apiVersion: apps/v1
metadata:
  name: mw-kube-agent
  namespace: "NAMESPACE_VALUE"
spec:
  selector:
    matchLabels:
      app: mw-app
  template:
    metadata:
      labels:
        app: mw-app
        k8s-app: mw-app
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoSchedule"
      - operator: "Exists"
        effect: "NoExecute"
      volumes:
        - name: mw-deployment-otel-config-volume
          configMap:
            name: mw-deployment-otel-config
            items:
              - key: otel-config
                path: otel-config-deployment.yaml

      containers:
        - args:
            - mw-agent
            - start
            - --otel-config-file
            - /app/otel-config-deployment.yaml
          volumeMounts:
            - name: mw-deployment-otel-config-volume
              mountPath: /app
          env:
            - name: MW_TARGET
              value: "TARGET_VALUE"
            - name: MW_API_KEY
              value: "MW_API_KEY_VALUE"
            - name: MW_DOCKER_ENDPOINT
              value: "MW_DOCKER_ENDPOINT_VALUE"
            - name: MW_KUBE_CLUSTER_NAME
              value: "MW_KUBE_CLUSTER_NAME_VALUE"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: ghcr.io/middleware-labs/mw-kube-agent:1.6.1
          imagePullPolicy: Always
          name: mw-kube-agent
          securityContext:
            privileged: true
          resources: {}
      restartPolicy: Always
      serviceAccountName: mw-service-account